import PDFDocument from 'pdfkit';

const CURRENCY_SYMBOLS = { NGN:'₦', USD:'$', GBP:'£', EUR:'€' };

function formatDate(iso) {
  if (!iso) return 'N/A';
  return new Date(iso).toLocaleString('en-NG', {
    weekday:'short', day:'numeric', month:'short', year:'numeric',
    hour:'2-digit', minute:'2-digit',
  });
}

/**
 * Generates a PDF invoice buffer for a booking.
 * Returns a Buffer.
 */
export function generateInvoicePDF(booking, company) {
  return new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin:50, size:'A4' });
    const chunks = [];
    doc.on('data',  chunk => chunks.push(chunk));
    doc.on('end',   () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const accent = '#2563eb';

    // ── Header ───────────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill(accent);
    doc.fillColor('#fff').fontSize(22).font('Helvetica-Bold')
       .text(company?.name || 'Ariva Transport', 50, 25, { width: doc.page.width - 100 });
    doc.fontSize(10).font('Helvetica')
       .text('INVOICE', 50, 52, { width: doc.page.width - 100, align: 'right' });
    doc.fillColor('#000');

    // ── Invoice meta ─────────────────────────────────────────────────────────
    const topY = 100;
    doc.fontSize(10).font('Helvetica-Bold').text('Reference:', 50, topY);
    doc.font('Helvetica').text(booking.reference || '—', 130, topY);

    doc.font('Helvetica-Bold').text('Date:', 50, topY + 16);
    doc.font('Helvetica').text(formatDate(booking.created), 130, topY + 16);

    doc.font('Helvetica-Bold').text('Status:', 50, topY + 32);
    doc.font('Helvetica').text((booking.status || '').replace(/_/g, ' ').toUpperCase(), 130, topY + 32);

    // ── Divider ───────────────────────────────────────────────────────────────
    doc.moveTo(50, topY + 55).lineTo(doc.page.width - 50, topY + 55).strokeColor('#e2e8f0').lineWidth(1).stroke();

    // ── Customer details ─────────────────────────────────────────────────────
    const custY = topY + 70;
    doc.fillColor(accent).fontSize(11).font('Helvetica-Bold').text('CUSTOMER', 50, custY);
    doc.fillColor('#000').fontSize(10).font('Helvetica');
    doc.text(booking.caller_name  || '—', 50, custY + 16);
    doc.text(booking.caller_phone || '—', 50, custY + 30);
    if (booking.customer_email) doc.text(booking.customer_email, 50, custY + 44);

    // ── Trip details ─────────────────────────────────────────────────────────
    const tripY = custY + (booking.customer_email ? 72 : 58);
    doc.fillColor(accent).fontSize(11).font('Helvetica-Bold').text('TRIP DETAILS', 50, tripY);
    doc.fillColor('#000').fontSize(10).font('Helvetica');

    const rows = [
      ['Pickup time',    formatDate(booking.pickup_datetime)],
      ['Pickup address', booking.pickup_address || '—'],
      ['Drop-off',       booking.dropoff_address || '—'],
      ['Duration',       booking.duration_hours ? `${booking.duration_hours} hour(s)` : '—'],
      ['Vehicle type',   booking.vehicle_type || '—'],
      ['Driver',         booking.driver || '—'],
      ['Flight number',  booking.flight_number || '—'],
      ['Notes',          booking.notes || '—'],
    ].filter(([, v]) => v !== '—');

    let rowY = tripY + 16;
    for (const [label, value] of rows) {
      doc.font('Helvetica-Bold').text(`${label}:`, 50, rowY, { width:120, continued:false });
      doc.font('Helvetica').text(value, 180, rowY, { width:350 });
      rowY += 16;
    }

    // ── Pricing ───────────────────────────────────────────────────────────────
    if (booking.quoted_price) {
      rowY += 12;
      doc.moveTo(50, rowY).lineTo(doc.page.width - 50, rowY).strokeColor('#e2e8f0').lineWidth(1).stroke();
      rowY += 16;

      const symbol   = CURRENCY_SYMBOLS[booking.quoted_currency] ?? '₦';
      const amount   = `${symbol}${Number(booking.quoted_price).toLocaleString()}`;
      const ruleNote = booking.pricing_rule ? ` (${booking.pricing_rule})` : '';

      doc.fillColor(accent).fontSize(11).font('Helvetica-Bold').text('AMOUNT DUE', 50, rowY);
      rowY += 16;
      doc.fillColor('#000').fontSize(16).font('Helvetica-Bold').text(amount + ruleNote, 50, rowY);
    }

    // ── Footer ─────────────────────────────────────────────────────────────────
    const footerY = doc.page.height - 60;
    doc.moveTo(50, footerY).lineTo(doc.page.width - 50, footerY).strokeColor('#e2e8f0').lineWidth(1).stroke();
    doc.fillColor('#94a3b8').fontSize(9).font('Helvetica')
       .text(
         `Generated by Ariva · ${company?.name || ''} · ${new Date().toLocaleDateString('en-NG')}`,
         50, footerY + 12,
         { align: 'center', width: doc.page.width - 100 }
       );

    doc.end();
  });
}
